### ISSUE TITLE
Why exit codes 42759 & 42758

### ISSUE THREAD

**Issue by ztzven** [ZitRos/node-graceful-shutdown#1]
What is significant about these numbers?

**Comment by nikitaeverywhere** [comment]
Hello!

I wanted to highlight abnormal exiting with something more meaningful than exit code `1`. Something that one can Google and find out that this code is due to the error in the error handler/shutdown handler. Don’t you think it’s a good idea?

Thanks

**Comment by ztzven** [comment]
Actually I quite like the meaningful exit.. identifies it came from this unique package..

**Comment by nikitaeverywhere** [comment]
😊
