### ISSUE TITLE
Parameter has a name but no type.

### ISSUE THREAD

**Issue by dbettoni** [ZitRos/node-graceful-shutdown#9]
When I compile my project which depends on
     "node-graceful-shutdown": "^1.1.0",
I get the error you see below.
Until 1.1.2 everything Ok the error occurs with 1.1.3
<img width="1116" alt="Schermata 2022-12-13 alle 12 43 53" src="https://user-images.githubusercontent.com/30083487/207310355-43ced206-c44e-4741-95ab-e60e69e09759.png">

**Comment by nikitaeverywhere** [comment]
Oops that was recent merge #8

**Comment by nikitaeverywhere** [comment]
Thanks a ton for reporting, should be fixed in 868f72c620e58cff5525fd1e34ee79b883f3a83c and now in v 1.1.4.

That was a syntax mistake. Can you test now?

**Comment by dbettoni** [comment]
Thanks, I tried with 1.1.4 now it's OK

**Comment by nikitaeverywhere** [comment]
I have also just published 1.1.5 where return type `void` is fixed to `unknown`, in case the type were breaking any existing code this should now be gone.

Also added typescript tests
